/*  
 * Copyright (c) 2017, Michinobu Maeda 
 * Licensed under the MIT License.
 * See LICENSE file in the project root for full license information.  
 */

export const getTop = jest.fn()
export const getGroups = jest.fn()
export const getGroup = jest.fn()
export const updateGroup = jest.fn()
export const deleteGroup = jest.fn()
export const createSubGroup = jest.fn()
export const addSubGroup = jest.fn()
export const removeSubGroup = jest.fn()
export const createMember = jest.fn()
export const addMember = jest.fn()
export const removeMember = jest.fn()
export const addOwner = jest.fn()
export const removeOwner = jest.fn()
export const getUsers = jest.fn()
export const getUser = jest.fn()
export const updateUser = jest.fn()
export const deleteUser = jest.fn()
export const getUserCerts = jest.fn()
export const createUserCert = jest.fn()
export const updateUserCert = jest.fn()
export const deleteUserCert = jest.fn()
export const getSessions = jest.fn()
export const createSession = jest.fn()
export const deleteSession = jest.fn()
export const deleteMySession = jest.fn()
export const revokeManager = jest.fn()
export const revokeAdmin = jest.fn()
export const createToken = jest.fn()
export const getLogs = jest.fn()
export const getHelps = jest.fn()
export const updateHelp = jest.fn()
