const iconList = {
  'OK': 'check',
  'Cancel': 'close',
  'Top': 'home',
  'Sign in': 'account_circle',
  'Sign out': 'power_settings_new',
  'Privacy policy': 'privacy_tip',
  'Categories': 'label',
  'Category': 'label',
  'Groups': 'group',
  'Group': 'group',
  'User': 'person',
  'Profile and Settings': 'contact_page',
  'Service': 'settings',
  'Edit': 'edit',
  'Add': 'add',
  'Delete': 'delete',
  'Undo delete': 'restore_from_trash',
  'Save': 'done',
  'Upward': 'arrow_upward',
  'Downward': 'arrow_downward',
  'E-mail': 'mail',
  'Visible': 'visibility',
  'Invisible': 'visibility_off',
  'Send': 'send',
  'Defaults': 'settings_applications',
  'Update app': 'system_update_alt',
  'Update service': 'sync',
  'Service settings': 'settings',
  'Raw data': 'memory'
}

export const icon = name => iconList[name] || 'description'
